language: node_js
node_js:
- 12
script:
- npm run test
deploy:
  provider: npm
  email: public.sjmallon@gmail.com
  on:
    tags: true
  api_key:
    secure: 0ovhGt6GM4nRH4nKwDraxc78Hmw73SKc3o/d6bXD7AxWDcBV2KuW6rrfF0GKAHfPDYcsOASSzJf7F6HzdS3B9CSRWMdB3D4zxfed83onvC4gytVLsMwRh5Qd5oqIEaaA1b2U0aOQ/hMRt6+xXBo68PWZODn+aGTHLmma48L/kEc1wjQkMqvhaVm/1i+QR/dB14UnodWLg+4Lv072YgK2V7R7fEdUBJC3jqKqI5oPiWf+N0KHTXJkgd5B+DvZQMP2/4FDZtgpqZYuJVSfPy06beQZJi+dAsHU+iriNmtXAH7pkDM390oKGxg9TiZDJ2NTolFOP6esgRJ9cLAxl3FUhMb+iCASQ5DsTyes8igjUL8B8BEzPPxRNl4mxWkWEFwLqxXFj/fpw31FqwX/7xwNdmot9ZIuk2dPAMEXb3PMsixATnPy2s/Ej6yfxAlY00glXCckO0B+LG0wFp2Ry/gKAltSHX4QwCp1cfXIgootIbERe+fJ165hqHHm+4htvxCjkU5K5K3WbsOeLW5BBg/ZMa6GVCwopyp7Re23tEgqC5MyDtvsnZOxxpEkRKEMFolTTMddekTPiLDxVmKzouMcA2C8K+2cY8/NmSANRZzpcMqFod0huJNiepD8t5oliHzKReJQlkzSfCK5AGz2IvZiTBLwa8XNVIPOMWaB1fQF/28=
