language: node_js
node_js:
  - 12
script:
  - npm run test
deploy:
  provider: npm
  edge: true
  email: public.sjmallon@gmail.com
  api_key:
    secure: JDB6zRSla90XvTaZ5iZu6S5lSMKVjBdXAeFiZb2UZMwWwTecFg4AdMSndQIVromgCD/6NHo7SEHA2aIirKPwrQgA2Nx0j/RMkj5N1lPNMpuqsUjIy9vL7ZsDdgzbE7GAvJqaMWjHs5Bwi7N/fON26VsL0ZlTQMB7n77ZiLPxz1luD7jTCnkbPTW0K4mV55OAHSjZDKYjmbCnPAguItrSgXxTLXNE/bj3eDPTaADcudXTz8DPUxuZeo8LL+1uLSgTh/yXb11NhADiGIIp0n2QZqRQs7PGFky7o7zeW5tzvbmpPgrWfPH11uo0nG8xXEodJTXapYOiLgOu4HVrXnCzgxWtM/kPsttZN/m5Xu2wHRb5hl0thzn2scohT1RIwEA/voqHyy5GtFqJHVeD/pJM0MHLWbKF7h96L5tqIYFsNNlXER9dLHU4YjVolrpKpYqEGt9LEkvYMOJ3IoQoYNUdhBB2jWMeVwU+QxmZmMHVQbMWiXq0cIttN24tdYE7VPm6asuEByjjrlfubPGPFYMUJkxjTi2nWDyJ0UVAKUk+0tzt+vTzPEVs0MNYsAtzS2w5BE5re86ckl/6TnrlEJVLVmV6ttCu6xuXNtC/Jdga32l8TlceWOKQrvkVQgsXmCmMgJDEnrXj59qJCmcdOfb99+uV/HlO4FV3LcSVwcr2HmY=
  on:
    tags: true
